# Generated by Django 3.0.11 on 2021-01-01 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_discorduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord_user', to=settings.AUTH_USER_MODEL, verbose_name='Related User'),
        ),
    ]
